#ifndef LOCAL_TYPES_H_INCLUDED
#define LOCAL_TYPES_H_INCLUDED

enum token_type{
    DOT = 0, COMMA, SEMICOLON, COLON,
    OPEN_PAR, CLOSE_PAR, OPEN_BRACE, CLOSE_BRACE,
    OPEN_BRACKET, CLOSE_BRACKET, PLUS, MINUS,
    TIMES, SLASH, EXCLAMATION, PERCENT, GREATER, LESS,
    ASSIGN, EQUAL, N_EQUAL, G_EQUAL,
    L_EQUAL, IDENTITY, N_IDENTITY,

    VAR, TRUE, FALSE, ARRAY, RESPONCE,
    ENVIRONMENT, NIL, UNDEFINED, TYPEOF,
    FUNCTION, IF, WHILE, FOR, ELSE, DO,
    IN, BREAK, CONTINUE, RETURN,

    ZERO, ENDOF, IDENTIFIER, BOOL, INT, STRING, REAL,
    RPN_GOTO, RPN_IFNOT_GOTO, RPN_LINK
};

#endif // LOCAL_TYPES_H_INCLUDED
